// faq-data.js — base de réponses de l'aide Kapitaro (source unique : page /faq et bulle d'aide en bas à droite).
// Chaque entrée : id, catégorie, question, réponse (HTML simple), mots-clés (sans accents, en minuscules) pour la reconnaissance.
window.KAPITARO_FAQ = [
  // ── Démarrer ──
  { id: 'gratuit', cat: 'Démarrer', q: 'Kapitaro est-il gratuit ?',
    a: 'Oui. La version gratuite n\'a pas de limite de durée et ne demande aucune carte bancaire. <b>Premium</b> (9,99 €/mois ou 79,99 €/an, sans engagement) ajoute l\'IA illimitée et des outils avancés.',
    keys: ['gratuit', 'payant', 'combien ca coute', 'prix', 'tarif', 'cout', 'free'] },
  { id: 'compte', cat: 'Démarrer', q: 'Comment créer un compte ?',
    a: 'Sur <a href="/">kapitaro.fr</a>, onglet <b>Inscription</b> : ton e-mail et un mot de passe (8 caractères minimum), ou <b>Continuer avec Google</b>. Confirme ensuite ton adresse avec le lien reçu par e-mail.',
    keys: ['creer un compte', 'inscription', 's inscrire', 'inscrire', 'ouvrir un compte', 'nouveau compte', 'register'] },
  { id: 'confirmation', cat: 'Démarrer', q: 'Je n\'ai pas reçu l\'e-mail de confirmation',
    a: 'Regarde dans tes <b>spams</b> et l\'onglet <b>Promotions</b> (expéditeur : bonjour@kapitaro.fr). Attends quelques minutes, puis réessaie de t\'inscrire. Si rien n\'arrive, écris-nous à <a href="mailto:contact@kapitaro.fr">contact@kapitaro.fr</a>.',
    keys: ['pas recu', 'email de confirmation', 'mail de confirmation', 'confirmer mon adresse', 'lien de confirmation', 'pas de mail', 'spam'] },
  { id: 'demo', cat: 'Démarrer', q: 'Puis-je essayer sans créer de compte ?',
    a: 'Oui : sur la page d\'accueil, clique sur <b>Essayer sans compte</b>. Tu explores l\'app avec un portefeuille fictif. L\'assistant IA et les notifications demandent un compte gratuit.',
    keys: ['sans compte', 'essayer', 'demo', 'tester', 'mode demo', 'decouvrir'] },
  { id: 'debutant', cat: 'Démarrer', q: 'Je débute complètement, par où commencer ?',
    a: 'Après l\'inscription, un <b>tutoriel en 4 étapes</b> te propose un premier plan adapté à ton niveau. Tu peux ensuite fixer un objectif dans <b>Objectif</b>, et poser tes questions à l\'<b>Agent IA</b>. Tu peux relancer le tutoriel dans <b>Paramètres → Aide</b>.',
    keys: ['debute', 'debutant', 'commencer', 'par ou commencer', 'jamais investi', 'tutoriel', 'tuto', 'guide'] },
  { id: 'motdepasse', cat: 'Démarrer', q: 'J\'ai oublié mon mot de passe',
    a: 'Sur l\'écran de connexion, clique sur <b>Mot de passe oublié ?</b> : tu reçois un e-mail pour en choisir un nouveau. Une fois connecté, tu peux aussi le changer dans <b>Paramètres → Connexion → Mot de passe</b>.',
    keys: ['mot de passe', 'oublie', 'password', 'reinitialiser', 'changer mon mot de passe', 'mdp', 'connexion impossible', 'je n arrive pas a me connecter'] },

  // ── Portefeuille ──
  { id: 'ajouter', cat: 'Portefeuille', q: 'Comment ajouter une action ou un ETF ?',
    a: 'Clique sur <b>+ Ajouter</b> (Accueil ou Portefeuille), cherche le nom ou le code du titre, puis indique la <b>quantité</b> et ton <b>prix de revient (PRU)</b>. Le prix se met ensuite à jour tout seul.',
    keys: ['ajouter', 'ajouter une action', 'ajouter un etf', 'ajouter une position', 'nouvelle position', 'rajouter', 'saisir', 'mettre une action'] },
  { id: 'importer', cat: 'Portefeuille', q: 'Puis-je importer mon relevé de courtier ?',
    a: 'Oui : dans <b>Portefeuille</b>, bouton <b>Importer mes positions</b>. Formats acceptés : <b>PDF, Excel ou CSV</b> (Trade Republic, Boursorama, Degiro, XTB, Fortuneo…). Tu vérifies les lignes et les PRU avant de valider.',
    keys: ['importer', 'import', 'releve', 'csv', 'excel', 'pdf', 'fichier', 'trade republic', 'boursorama', 'degiro', 'xtb', 'fortuneo', 'courtier'] },
  { id: 'pru', cat: 'Portefeuille', q: 'C\'est quoi le PRU ?',
    a: 'Le <b>prix de revient unitaire</b> : le prix moyen auquel tu as acheté une part, frais inclus. Kapitaro s\'en sert pour calculer ta plus ou moins-value. Tu le trouves sur ton relevé de courtier.',
    keys: ['pru', 'prix de revient', 'prix moyen', 'prix d achat', 'plus value', 'moins value'] },
  { id: 'modifier', cat: 'Portefeuille', q: 'Comment modifier ou supprimer une position ?',
    a: 'Dans <b>Portefeuille</b>, clique sur la position pour modifier la quantité ou le PRU, ou la supprimer. Le bouton <b>Sélectionner</b> permet d\'en traiter plusieurs d\'un coup.',
    keys: ['modifier', 'supprimer une position', 'effacer', 'corriger', 'changer la quantite', 'enlever', 'retirer une action'] },
  { id: 'prix', cat: 'Portefeuille', q: 'Les prix sont-ils en temps réel ?',
    a: 'Les cours viennent de fournisseurs de données de marché et se mettent à jour régulièrement. Ils peuvent être <b>légèrement différés</b> et sont donnés à titre indicatif.',
    keys: ['temps reel', 'prix', 'cours', 'mise a jour', 'differe', 'prix faux', 'pas a jour', 'cotation'] },
  { id: 'courtier', cat: 'Portefeuille', q: 'Kapitaro a-t-il accès à mon compte chez mon courtier ?',
    a: 'Non. Kapitaro ne se connecte à <b>aucune banque ni aucun courtier</b> et ne peut passer <b>aucun ordre</b> : tu ajoutes toi-même tes positions ou tu importes un relevé.',
    keys: ['acces a mon compte', 'connecter ma banque', 'connecter mon courtier', 'passer un ordre', 'acheter depuis', 'synchroniser', 'lier mon compte'] },

  // ── Outils ──
  { id: 'score', cat: 'Outils', q: 'Comment est calculé le score de santé ?',
    a: 'C\'est une note sur 10 qui combine la <b>diversification</b>, la <b>concentration</b> (poids de ta plus grosse ligne), la <b>part d\'ETF</b> et la <b>performance</b>. La page <b>Santé</b> t\'indique quoi améliorer en priorité.',
    keys: ['score', 'sante', 'note', 'sur 10', 'diversification', 'concentration'] },
  { id: 'objectif', cat: 'Outils', q: 'Comment fixer un objectif ?',
    a: 'Page <b>Objectif</b> : indique ton capital de départ, ton versement mensuel et la somme visée. Kapitaro te dit si c\'est atteignable, en combien de temps, et propose un plan mois par mois.',
    keys: ['objectif', 'but', 'projet', 'plan', 'projection', 'atteindre'] },
  { id: 'decision', cat: 'Outils', q: 'À quoi sert l\'aide à la décision ?',
    a: 'Tu hésites à acheter ou vendre ? Page <b>Aide à la décision</b> : choisis le titre, le montant et ton intention. Tu obtiens une analyse chiffrée pour t\'aider à réfléchir. La décision reste la tienne.',
    keys: ['aide a la decision', 'decision', 'hesite', 'analyser une action', 'analyse'] },
  { id: 'simulateurs', cat: 'Outils', q: 'Quels simulateurs sont disponibles ?',
    a: 'Dans l\'app : <b>Simulateur DCA</b> (investir chaque mois) et <b>Scénario crise</b> (impact d\'une baisse des marchés). Sans compte : <a href="/simulateur-interets-composes">intérêts composés</a>, <a href="/calculateur-objectif-epargne">objectif d\'épargne</a>, <a href="/rendement-etf-msci-world">ETF MSCI World</a>, <a href="/epargne-de-precaution">épargne de précaution</a>, <a href="/simulateur-investissement-programme">investissement programmé</a>, <a href="/calculateur-frais-placement">impact des frais</a> et <a href="/calculateur-inflation">inflation</a>.',
    keys: ['simulateur', 'dca', 'crise', 'scenario', 'interets composes', 'calculateur', 'simuler', 'outils gratuits'] },
  { id: 'agent', cat: 'Outils', q: 'Comment fonctionne l\'Agent IA ?',
    a: 'Onglet <b>Agent IA</b> : pose tes questions sur ton portefeuille en français. Version gratuite : <b>15 analyses offertes, puis 3 par jour</b>. Premium : analyses illimitées et Agent IA complet.',
    keys: ['agent', 'assistant', 'ia', 'intelligence artificielle', 'chat', 'poser une question', 'quota', 'limite ia', 'analyses'] },
  { id: 'depenses', cat: 'Outils', q: 'À quoi sert la page Mes dépenses ?',
    a: 'Avec <b>Premium</b>, importe ton relevé de compte bancaire : Kapitaro classe tes dépenses, repère tes abonnements et te montre ce que tu économiserais en investissant la différence.',
    keys: ['depenses', 'budget', 'abonnements', 'releve bancaire', 'economies'] },
  { id: 'bilan', cat: 'Outils', q: 'Qu\'est-ce que le bilan patrimonial ?',
    a: 'Avec <b>Premium</b> : un bilan complet de ta situation (épargne, objectifs, placements) avec un plan d\'action chiffré, exportable en PDF. Tu le retrouves dans <b>Mon bilan</b>.',
    keys: ['bilan', 'patrimoine', 'patrimonial', 'pdf'] },

  // ── Premium & paiement ──
  { id: 'premium', cat: 'Premium & paiement', q: 'Que contient Premium ?',
    a: 'Analyses IA illimitées, Agent IA complet, bilan patrimonial avec export PDF, analyse de tes dépenses et conseils IA sur tes alertes. <b>9,99 €/mois</b> ou <b>79,99 €/an</b>, sans engagement.',
    keys: ['premium', 'abonnement', 'offre', 'avantages', 'difference gratuit', 'illimite'] },
  { id: 'souscrire', cat: 'Premium & paiement', q: 'Comment passer à Premium ?',
    a: 'Menu → <b>Passez à Premium</b>, ou <b>Paramètres → Abonnement → Voir Premium</b>. Le paiement se fait par carte, de façon sécurisée, via <b>Stripe</b>.',
    keys: ['passer premium', 'souscrire', 's abonner', 'abonner', 'acheter premium', 'payer'] },
  { id: 'codepromo', cat: 'Premium & paiement', q: 'Où saisir un code promo ?',
    a: 'Sur la page de paiement (Stripe), clique sur <b>Ajouter un code promotionnel</b> avant de valider, puis colle ton code.',
    keys: ['code promo', 'promo', 'reduction', 'coupon', 'code de reduction', 'promotionnel'] },
  { id: 'resilier', cat: 'Premium & paiement', q: 'Comment résilier mon abonnement ?',
    a: '<b>Paramètres → Abonnement → Gérer</b>. Tu peux résilier en un clic ; tu gardes Premium jusqu\'à la fin de la période déjà payée. Tu y trouves aussi tes factures et ton moyen de paiement.',
    keys: ['resilier', 'annuler', 'arreter', 'desabonner', 'stopper', 'resiliation', 'fin abonnement'] },
  { id: 'factures', cat: 'Premium & paiement', q: 'Où trouver mes factures ?',
    a: '<b>Paramètres → Abonnement → Gérer</b> : l\'espace sécurisé Stripe affiche tes factures, à télécharger en PDF.',
    keys: ['facture', 'factures', 'recu', 'justificatif', 'carte bancaire', 'moyen de paiement', 'changer de carte'] },
  { id: 'securite-paiement', cat: 'Premium & paiement', q: 'Le paiement est-il sécurisé ?',
    a: 'Oui : il passe par <b>Stripe</b>, un prestataire de paiement reconnu. Kapitaro ne voit et ne stocke jamais les numéros de carte.',
    keys: ['paiement securise', 'securise', 'stripe', 'numero de carte', 'fraude'] },

  // ── Compte & données ──
  { id: 'donnees', cat: 'Compte & données', q: 'Mes données sont-elles protégées ?',
    a: 'Elles sont chiffrées lors des échanges, hébergées de façon sécurisée et <b>jamais vendues</b>. Détails dans la <a href="/confidentialite">politique de confidentialité</a>.',
    keys: ['donnees', 'securite', 'confidentialite', 'vie privee', 'rgpd', 'protege', 'vendues'] },
  { id: 'export', cat: 'Compte & données', q: 'Comment télécharger mes données ?',
    a: '<b>Paramètres → Mes données</b> : <b>Rapport PDF du portefeuille</b>, ou <b>Télécharger toutes mes données</b> (un fichier avec tout ce que Kapitaro garde sur toi).',
    keys: ['telecharger mes donnees', 'exporter', 'export', 'recuperer mes donnees', 'rapport pdf'] },
  { id: 'supprimer', cat: 'Compte & données', q: 'Comment supprimer mon compte ?',
    a: '<b>Paramètres</b>, tout en bas : <b>Supprimer mon compte</b>. Toutes tes données sont effacées définitivement. Pense à résilier Premium avant si tu es abonné.',
    keys: ['supprimer mon compte', 'supprimer le compte', 'effacer mon compte', 'fermer mon compte', 'desinscription'] },
  { id: 'emails', cat: 'Compte & données', q: 'Comment ne plus recevoir vos e-mails ?',
    a: 'Clique sur <b>Ne plus recevoir ces e-mails</b> en bas d\'un de nos e-mails, ou désactive <b>E-mails de conseils et rappels</b> dans <b>Paramètres → Notifications</b>.',
    keys: ['emails', 'mails', 'newsletter', 'ne plus recevoir', 'desabonner des mails', 'trop de mails'] },
  { id: 'conseil', cat: 'Compte & données', q: 'Kapitaro donne-t-il des conseils en investissement ?',
    a: 'Non. Kapitaro est un <b>outil pédagogique</b> d\'aide à la décision : il t\'aide à comprendre et organiser tes placements, mais la décision finale t\'appartient. Investir comporte un risque de perte en capital.',
    keys: ['conseil', 'conseiller', 'amf', 'recommandation', 'regle', 'agree'] },

  // ── Application & notifications ──
  { id: 'installer', cat: 'Application & notifications', q: 'Comment installer l\'app sur mon téléphone ?',
    a: 'Pas besoin de store : ouvre <b>kapitaro.fr</b> dans ton navigateur. <b>Android (Chrome)</b> : bouton <b>Installer l\'app</b>, ou menu ⋮ → Installer l\'application. <b>iPhone (Safari)</b> : bouton Partager ⬆️ → <b>Sur l\'écran d\'accueil</b>.',
    keys: ['installer', 'installation', 'application', 'app', 'telecharger l app', 'iphone', 'android', 'ecran d accueil', 'play store', 'app store'] },
  { id: 'notifications', cat: 'Application & notifications', q: 'Comment activer les notifications ?',
    a: '<b>Paramètres → Notifications</b> : active <b>Notifications sur cet appareil</b>. Tu reçois ton briefing du matin et une alerte quand un prix passe sous ton seuil. Sur iPhone, installe d\'abord l\'app sur l\'écran d\'accueil.',
    keys: ['notification', 'notifications', 'alerte', 'alertes', 'briefing', 'push', 'etre prevenu'] },
  { id: 'theme', cat: 'Application & notifications', q: 'Peut-on passer en mode sombre ?',
    a: 'Oui : bouton <b>Sombre / Clair</b> en haut de l\'app, ou <b>Paramètres → Apparence → Thème</b>.',
    keys: ['sombre', 'mode sombre', 'theme', 'dark', 'clair', 'couleur'] },
  { id: 'contact', cat: 'Application & notifications', q: 'Comment vous contacter ?',
    a: 'Écris-nous à <a href="mailto:contact@kapitaro.fr">contact@kapitaro.fr</a>, on répond rapidement.',
    keys: ['contact', 'contacter', 'support', 'joindre', 'humain', 'probleme', 'bug', 'reclamation', 'email'] },
];

// Réponse aux demandes de conseil personnalisé (la bulle d'aide ne recommande jamais de titre)
window.KAPITARO_FAQ_ADVICE = {
  keys: ['quelle action', 'quoi acheter', 'dois je acheter', 'dois je vendre', 'faut il acheter', 'faut il vendre', 'meilleure action', 'meilleur etf', 'investir dans', 'que me conseilles', 'bon moment', 'va monter', 'va baisser', 'crypto', 'bitcoin'],
  a: 'Je réponds uniquement aux questions sur l\'utilisation de Kapitaro, et je ne donne pas de conseil d\'investissement. Pour analyser une idée, utilise la page <b>Aide à la décision</b> ou l\'<b>Agent IA</b> de l\'app.'
};
